### PR TITLE
Bound certain adjusted controls

### PR DESCRIPTION
**Pull request by ifenty**
Adds zero bounds to the following adjusted fields

#ifdef EXF_ZERO_BOUND_AQH 
#ifdef EXF_ZERO_BOUND_PRECIP
#ifdef EXF_ZERO_BOUND_SWDOWN
#ifdef EXF_ZERO_BOUND_LWDOWN
#ifdef EXF_ZERO_BOUND_RUNOFF

max(field, 0. _0)

All of these fields have physical values of  0 >= FIELD

### CODE REVIEW

**Comment by menemenlis** [comment]
Hi Ian, my first git comment!  One caveat is that for shortwave this will not fix spurious nighttime values.  For shortwave we could use Matt's correction "for SW>0, mask=1; and mask=0 for SW=0; then NEW = OLD + xx * mask;".  But we should find out what Hong meant by "still could have problem".

**Comment by ifenty** [comment]
@menemenlis this is good idea, and a small change I can easily make. 

please see my comment https://github.com/ECCO-GROUP/ECCO-v4-Configurations/issues/56#issuecomment-661576959

**Comment by ifenty** [comment]
#60 done.

**Comment by hongandyan** [comment]
> Hi Ian, my first git comment! One caveat is that for shortwave this will not fix spurious nighttime values. For shortwave we could use Matt's correction "for SW>0, mask=1; and mask=0 for SW=0; then NEW = OLD + xx * mask;". But we should find out what Hong meant by "still could have problem".

I mean, suppose a case where SW is 5 w/m^2 and xx is -6w/m^2, it will end up with -1 w/m^2 :-)

**Comment by ifenty** [comment]
Hi @hongandyan  Your first git comment is a good one!

The issue you raise is now handled in #59 and #60.  Only if SW > 0 can there be *any* adjustment.  Then, if the correct ifdef is supplied, SW will be bounded by 0 >= SW > flaming hot supernova

please see my comments #56 (comment), especially the request to transition the llc270 setup to the more recent v4r5 devel base.

However, if SW >0, no matter how small, there is no **UPPER** bound to the adjusted value.  We could improve the control code by having the uncertainty in SW be a function of the SW itself.

**Pull request merged**
